sudo: false
language: node_js
node_js:
  - stable
cache:
  bundle: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
after_success:
  - git config --global user.name "rtnogueira"
  - git config --global user.email "14441214+rtnogueira@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://rtnogueira:${$GITHUB_TOKEN}@github.com/rtnogueira/nif-generator.git
  - yarn run deploy